# Generated by Django 4.2.2 on 2026-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="token"
            ),
        ),
    ]
