# Generated by Django 4.2.2 on 2026-07-10 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Иван", max_length=100)),
                ("last_name", models.CharField(default="Иванов", max_length=100)),
                ("phone", models.CharField(default=70000000, max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Создание записи",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Изменение записи",
                    ),
                ),
                ("order_day", models.DateField(blank=True, null=True)),
                ("order_time", models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
