# Generated by Django 4.2.2 on 2026-07-10 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medical_website", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название услуги",
                        max_length=100,
                        unique=True,
                        verbose_name="Название услуга",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание услуги",
                        null=True,
                        verbose_name="Описание услуги",
                    ),
                ),
                ("preview", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "price",
                    models.IntegerField(
                        default=0,
                        help_text="Укажите стоимость услуги",
                        verbose_name="Стоимость услуги",
                    ),
                ),
                ("working_day", models.IntegerField(blank=True, null=True)),
                ("working_month", models.IntegerField(blank=True, null=True)),
                ("working_hour", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите специализацию",
                        max_length=100,
                        unique=True,
                        verbose_name="название специализация",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение специализации",
                        null=True,
                        upload_to="",
                        verbose_name="Изображение специализации",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание специализации",
                        verbose_name="Описание специализации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
            },
        ),
        migrations.CreateModel(
            name="ServicesService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="medical_website.service",
                    ),
                ),
            ],
            bases=("medical_website.service",),
        ),
        migrations.AddField(
            model_name="service",
            name="specialization",
            field=models.ForeignKey(
                help_text="Укажите специализацию",
                on_delete=django.db.models.deletion.CASCADE,
                to="medical_website.specialization",
                verbose_name="Специализация",
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Медицинский работник",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_website.specialization",
                        verbose_name="Специализация",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medical_website.service",
                verbose_name="Услуга",
            ),
        ),
    ]
